<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasTimestamps;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class FileImport extends Model
{
    use HasTimestamps, HasFactory;

    protected $table = 'file_imports';
    protected $fillable = ['name', 'path', 'import_by', 'state'];
    protected $guarded = ['id'];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::deleted(function ($model) {
            Storage::delete($model->path);
        });
    }

    public function transactionFailed(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(TransactionFail::class, 'file_import_id');
    }
}
